(function($){"use strict";$.fn.sliderResponsive=function(settings){var set=$.extend({slidePause:5000,fadeSpeed:800,autoPlay:"on",showArrows:"off",hideDots:"off",hoverZoom:"on",titleBarTop:"off",},settings);var $slider=$(this);var size=$slider.find("> div").length;var position=0;var sliderIntervalID;$slider.append("<ul></ul>");$slider.find("> div").each(function(){$slider.find("> ul").append("<li></li>");});$slider.find("div:first-of-type").addClass("show");$slider.find("li:first-of-type").addClass("showli");$slider.find("> div").not(".show").fadeOut();if(set.autoPlay==="on"){startSlider();}
if(set.showArrows==="on"){$slider.addClass("showArrows");}
if(set.hideDots==="on"){$slider.addClass("hideDots");}
if(set.hoverZoom==="off"){$slider.addClass("hoverZoomOff");}
if(set.titleBarTop==="on"){$slider.addClass("titleBarTop");}
function startSlider(){sliderIntervalID=setInterval(function(){nextSlide();},set.slidePause);}
$slider.mouseover(function(){clearInterval(sliderIntervalID);});$slider.mouseout(function(){startSlider();});$slider.find("> .right").click(nextSlide);$slider.find("> .left").click(prevSlide);function nextSlide(){position=$slider.find(".show").index()+1;if(position>size-1)position=0;changeCarousel(position);}
function prevSlide(){position=$slider.find(".show").index()-1;if(position<0)position=size-1;changeCarousel(position);}
$slider.find(" > ul > li").click(function(){position=$(this).index();changeCarousel($(this).index());});function changeCarousel(){$slider.find(".show").removeClass("show").fadeOut();$slider.find("> div").eq(position).fadeIn(set.fadeSpeed).addClass("show");$slider.find("> ul").find(".showli").removeClass("showli");$slider.find("> ul > li").eq(position).addClass("showli");}
return $slider;};})(jQuery);$(document).ready(function(){$("#slider1").sliderResponsive({});$("#slider2").sliderResponsive({fadeSpeed:300,autoPlay:"off",showArrows:"on",hideDots:"on",});$("#slider3").sliderResponsive({hoverZoom:"off",hideDots:"on",});});$('[data-fancybox="gallery"]').fancybox({buttons:["slideShow","thumbs","zoom","fullScreen","share","close"],loop:false,protect:true,});var currentImage;var thumbnails,thumbnailButtons;window.addEventListener("DOMContentLoaded",function(e){currentImage=document.querySelector(".current-image");$(".thumbnails").on("init",function(e,slick){thumbnailButtons=document.querySelectorAll(".thumbnails .thumbnail .thumbnail-button");thumbnailButtons.forEach(function(thumbnailButton){thumbnailButton.addEventListener("click",function(e){activateThumbnail(thumbnailButton);});});});$(".thumbnails").slick({slidesToShow:3,prevArrow:'<button class="previous-button button">'+
'  <span class="fas fa-angle-left" aria-hidden="true"></span>'+
'  <span class="sr-only">Previous slide</span>'+
"</button>",nextArrow:'<button class="next-button button">'+
'  <span class="fas fa-angle-right" aria-hidden="true"></span>'+
'  <span class="sr-only">Next slide</span>'+
"</button>",infinite:false,responsive:[{breakpoint:300,settings:{slidesToShow:1,},},],});function activateThumbnail(thumbnailButton){var newImageSrc=thumbnailButton.querySelector("img").getAttribute("src");var newImageAlt=thumbnailButton.querySelector("img").getAttribute("data-full-alt");currentImage.querySelector("img").setAttribute("src",newImageSrc);currentImage.querySelector("img").setAttribute("alt",newImageAlt);thumbnailButtons.forEach(function(button){button.removeAttribute("aria-current");});thumbnailButton.setAttribute("aria-current",true);}});(function(){"use strict";var carousels=function(){$(".owl-carousel1").owlCarousel({loop:true,center:true,margin:0,responsiveClass:true,nav:false,responsive:{0:{items:1,nav:false},680:{items:2,nav:false,loop:false},1000:{items:3,nav:true}}});};(function($){carousels();})(jQuery);})();